/**
 * Master Data 38 Provinsi & Kota/Kabupaten Seluruh Indonesia
 * TonalZone Localized Logistics Hub
 */

export interface RegionData {
  province: string;
  cities: string[];
}

export const INDONESIA_REGIONS: Record<string, string[]> = {
  "DKI Jakarta": [
    "Jakarta Selatan (Kebayoran, Senopati, SCBD)",
    "Jakarta Pusat (Menteng, Thamrin, Sudirman)",
    "Jakarta Barat (Puri Indah, Kebon Jeruk, Tomang)",
    "Jakarta Utara (PIK, Kelapa Gading, Pluit)",
    "Jakarta Timur (Rawamangun, Duren Sawit, Cakung)",
    "Kepulauan Seribu",
  ],
  "Jawa Barat": [
    "Kota Bandung (Dago, Ciumbuleuit, Buahbatu)",
    "Kab. Bandung (Soreang)",
    "Kab. Bandung Barat (Ngamprah)",
    "Kota Bekasi (Summarecon, Harapan Indah)",
    "Kab. Bekasi (Cikarang)",
    "Kota Depok (Margonda, Cinere, Sawangan)",
    "Kota Bogor (Pajajaran, Sentul)",
    "Kab. Bogor (Cibinong)",
    "Kota Cimahi",
    "Kota Cirebon",
    "Kab. Cirebon",
    "Kota Sukabumi",
    "Kab. Sukabumi",
    "Kota Tasikmalaya",
    "Kab. Tasikmalaya",
    "Kab. Garut",
    "Kab. Karawang",
    "Kab. Purwakarta",
    "Kab. Subang",
    "Kab. Sumedang",
    "Kab. Indramayu",
    "Kab. Majalengka",
    "Kab. Kuningan",
    "Kab. Ciamis",
    "Kab. Pangandaran",
    "Kota Banjar",
  ],
  "Jawa Timur": [
    "Kota Surabaya (Gubeng, Wonokromo, Pakuwon)",
    "Kota Malang (Klojen, Lowokwaru, Blimbing)",
    "Kab. Malang (Kepanjen)",
    "Kota Batu",
    "Kab. Sidoarjo (Waru, Kota)",
    "Kab. Gresik",
    "Kota Pasuruan",
    "Kab. Pasuruan",
    "Kota Probolinggo",
    "Kab. Probolinggo",
    "Kota Kediri",
    "Kab. Kediri",
    "Kota Blitar",
    "Kab. Blitar",
    "Kota Madiun",
    "Kab. Madiun",
    "Kota Mojokerto",
    "Kab. Mojokerto",
    "Kab. Jombang",
    "Kab. Banyuwangi",
    "Kab. Jember",
    "Kab. Lamongan",
    "Kab. Bojonegoro",
    "Kab. Tuban",
    "Kab. Nganjuk",
    "Kab. Tulungagung",
    "Kab. Trenggalek",
    "Kab. Ponorogo",
    "Kab. Pacitan",
    "Kab. Magetan",
    "Kab. Ngawi",
    "Kab. Lumajang",
    "Kab. Bondowoso",
    "Kab. Situbondo",
    "Kab. Bangkalan",
    "Kab. Sampang",
    "Kab. Pamekasan",
    "Kab. Sumenep",
  ],
  "Jawa Tengah": [
    "Kota Semarang (Simpang Lima, Candisari)",
    "Kab. Semarang (Ungaran)",
    "Kota Surakarta / Solo (Banjarsari, Laweyan)",
    "Kab. Sukoharjo (Solo Baru)",
    "Kab. Boyolali",
    "Kab. Klaten",
    "Kab. Karanganyar",
    "Kab. Wonogiri",
    "Kab. Sragen",
    "Kota Salatiga",
    "Kota Magelang",
    "Kab. Magelang",
    "Kota Pekalongan",
    "Kab. Pekalongan",
    "Kota Tegal",
    "Kab. Tegal (Slawi)",
    "Kab. Banyumas (Purwokerto)",
    "Kab. Cilacap",
    "Kab. Purbalingga",
    "Kab. Banjarnegara",
    "Kab. Kebumen",
    "Kab. Purworejo",
    "Kab. Wonosobo",
    "Kab. Temanggung",
    "Kab. Kendal",
    "Kab. Batang",
    "Kab. Pemalang",
    "Kab. Brebes",
    "Kab. Kudus",
    "Kab. Pati",
    "Kab. Jepara",
    "Kab. Rembang",
    "Kab. Blora",
    "Kab. Grobogan (Purwodadi)",
    "Kab. Demak",
  ],
  "DI Yogyakarta": [
    "Kota Yogyakarta (Malioboro, Kotagede)",
    "Kab. Sleman (Depok, Mlati, Kaliurang)",
    "Kab. Bantul",
    "Kab. Kulon Progo (Wates)",
    "Kab. Gunungkidul (Wonosari)",
  ],
  Banten: [
    "Kota Tangerang (Karawaci, Cipondoh)",
    "Kota Tangerang Selatan (BSD City, Bintaro, Alam Sutera)",
    "Kab. Tangerang (Gading Serpong, Cikupa)",
    "Kota Serang",
    "Kab. Serang",
    "Kota Cilegon",
    "Kab. Pandeglang",
    "Kab. Lebak (Rangkasbitung)",
  ],
  Bali: [
    "Kota Denpasar (Renon, Sanur)",
    "Kab. Badung (Kuta, Seminyak, Canggu, Nusa Dua)",
    "Kab. Gianyar (Ubud)",
    "Kab. Tabanan",
    "Kab. Buleleng (Singaraja)",
    "Kab. Jembrana (Negara)",
    "Kab. Klungkung",
    "Kab. Bangli",
    "Kab. Karangasem",
  ],
  "Sumatera Utara": [
    "Kota Medan",
    "Kota Binjai",
    "Kota Pematangsiantar",
    "Kab. Deli Serdang",
    "Kab. Karo (Berastagi)",
    "Kota Tebing Tinggi",
    "Kota Tanjungbalai",
    "Kota Sibolga",
    "Kota Padangsidimpuan",
    "Kota Gunungsitoli",
    "Kab. Asahan",
    "Kab. Langkat",
    "Kab. Simalungun",
    "Kab. Toba",
  ],
  "Sumatera Barat": [
    "Kota Padang",
    "Kota Bukittinggi",
    "Kota Payakumbuh",
    "Kota Solok",
    "Kota Sawahlunto",
    "Kota Padang Panjang",
    "Kota Pariaman",
    "Kab. Agam",
    "Kab. Tanah Datar",
    "Kab. Pesisir Selatan",
  ],
  Riau: [
    "Kota Pekanbaru",
    "Kota Dumai",
    "Kab. Kampar",
    "Kab. Siak",
    "Kab. Bengkalis",
    "Kab. Rokan Hulu",
    "Kab. Rokan Hilir",
    "Kab. Pelalawan",
    "Kab. Indragiri Hulu",
    "Kab. Indragiri Hilir",
  ],
  "Kepulauan Riau": [
    "Kota Batam",
    "Kota Tanjungpinang",
    "Kab. Bintan",
    "Kab. Karimun",
    "Kab. Natuna",
    "Kab. Anambas",
    "Kab. Lingga",
  ],
  "Sumatera Selatan": [
    "Kota Palembang",
    "Kota Prabumulih",
    "Kota Lubuklinggau",
    "Kota Pagar Alam",
    "Kab. Banyuasin",
    "Kab. Ogan Ilir",
    "Kab. Ogan Komering Ilir",
    "Kab. Muara Enim",
    "Kab. Lahat",
  ],
  Lampung: [
    "Kota Bandar Lampung",
    "Kota Metro",
    "Kab. Lampung Selatan",
    "Kab. Lampung Tengah",
    "Kab. Lampung Timur",
    "Kab. Pringsewu",
    "Kab. Pesawaran",
  ],
  Aceh: [
    "Kota Banda Aceh",
    "Kota Sabang",
    "Kota Lhokseumawe",
    "Kota Langsa",
    "Kota Subulussalam",
    "Kab. Aceh Besar",
    "Kab. Pidie",
    "Kab. Bireuen",
    "Kab. Aceh Tengah (Takengon)",
  ],
  Jambi: [
    "Kota Jambi",
    "Kota Sungai Penuh",
    "Kab. Muaro Jambi",
    "Kab. Batanghari",
    "Kab. Bungo",
    "Kab. Merangin",
    "Kab. Kerinci",
  ],
  Bengkulu: [
    "Kota Bengkulu",
    "Kab. Rejang Lebong",
    "Kab. Bengkulu Selatan",
    "Kab. Bengkulu Utara",
    "Kab. Mukomuko",
  ],
  "Kepulauan Bangka Belitung": [
    "Kota Pangkalpinang",
    "Kab. Bangka (Sungailiat)",
    "Kab. Belitung (Tanjung Pandan)",
    "Kab. Bangka Barat",
    "Kab. Bangka Tengah",
    "Kab. Bangka Selatan",
    "Kab. Belitung Timur",
  ],
  "Kalimantan Barat": [
    "Kota Pontianak",
    "Kota Singkawang",
    "Kab. Kubu Raya",
    "Kab. Mempawah",
    "Kab. Sambas",
    "Kab. Ketapang",
    "Kab. Sintang",
  ],
  "Kalimantan Timur": [
    "Kota Balikpapan",
    "Kota Samarinda",
    "Kota Bontang",
    "Kab. Kutai Kartanegara (Tenggarong)",
    "Kab. Penajam Paser Utara (IKN Nusantara)",
    "Kab. Berau",
  ],
  "Kalimantan Selatan": [
    "Kota Banjarmasin",
    "Kota Banjarbaru",
    "Kab. Banjar (Martapura)",
    "Kab. Tanah Bumbu",
    "Kab. Kotabaru",
    "Kab. Tabalong",
  ],
  "Kalimantan Tengah": [
    "Kota Palangkaraya",
    "Kab. Kotawaringin Timur (Sampit)",
    "Kab. Kotawaringin Barat (Pangkalan Bun)",
    "Kab. Kapuas",
  ],
  "Kalimantan Utara": [
    "Kota Tarakan",
    "Kab. Bulungan (Tanjung Selor)",
    "Kab. Nunukan",
    "Kab. Malinau",
  ],
  "Sulawesi Selatan": [
    "Kota Makassar",
    "Kota Parepare",
    "Kota Palopo",
    "Kab. Gowa",
    "Kab. Maros",
    "Kab. Bone",
    "Kab. Bulukumba",
    "Kab. Tana Toraja",
  ],
  "Sulawesi Utara": [
    "Kota Manado",
    "Kota Tomohon",
    "Kota Bitung",
    "Kota Kotamobagu",
    "Kab. Minahasa",
    "Kab. Minahasa Utara",
  ],
  "Sulawesi Tengah": [
    "Kota Palu",
    "Kab. Donggala",
    "Kab. Poso",
    "Kab. Banggai (Luwuk)",
    "Kab. Tolitoli",
  ],
  "Sulawesi Tenggara": [
    "Kota Kendari",
    "Kota Baubau",
    "Kab. Konawe",
    "Kab. Kolaka",
    "Kab. Wakatobi",
  ],
  "Sulawesi Barat": [
    "Kab. Mamuju",
    "Kab. Polewali Mandar",
    "Kab. Majene",
    "Kab. Mamasa",
  ],
  Gorontalo: [
    "Kota Gorontalo",
    "Kab. Gorontalo",
    "Kab. Bone Bolango",
    "Kab. Boalemo",
  ],
  "Nusa Tenggara Barat": [
    "Kota Mataram (Lombok)",
    "Kab. Lombok Barat",
    "Kab. Lombok Tengah (Mandalika)",
    "Kab. Lombok Timur",
    "Kota Bima",
    "Kab. Sumbawa",
  ],
  "Nusa Tenggara Timur": [
    "Kota Kupang",
    "Kab. Manggarai Barat (Labuan Bajo)",
    "Kab. Flores Timur",
    "Kab. Sikka (Maumere)",
    "Kab. Ende",
    "Kab. Sumba Timur",
  ],
  Maluku: [
    "Kota Ambon",
    "Kota Tual",
    "Kab. Maluku Tengah",
    "Kab. Buru",
    "Kab. Kepulauan Aru",
  ],
  "Maluku Utara": [
    "Kota Ternate",
    "Kota Tidore Kepulauan",
    "Kab. Halmahera Utara",
    "Kab. Halmahera Selatan",
  ],
  Papua: [
    "Kota Jayapura",
    "Kab. Jayapura (Sentani)",
    "Kab. Keerom",
    "Kab. Biak Numfor",
    "Kab. Kepulauan Yapen (Serui)",
  ],
  "Papua Barat": [
    "Kab. Manokwari",
    "Kab. Fakfak",
    "Kab. Kaimana",
    "Kab. Teluk Bintuni",
  ],
  "Papua Barat Daya": [
    "Kota Sorong",
    "Kab. Sorong",
    "Kab. Raja Ampat",
  ],
  "Papua Selatan": [
    "Kab. Merauke",
    "Kab. Boven Digoel",
    "Kab. Mappi",
    "Kab. Asmat",
  ],
  "Papua Tengah": [
    "Kab. Nabire",
    "Kab. Mimika (Timika)",
    "Kab. Paniai",
    "Kab. Puncak Jaya",
  ],
  "Papua Pegunungan": [
    "Kab. Jayawijaya (Wamena)",
    "Kab. Yahukimo",
    "Kab. Tolikara",
    "Kab. Pegunungan Bintang",
  ],
};

export const INDONESIA_PROVINCES = Object.keys(INDONESIA_REGIONS);

export function getProvinces(): string[] {
  return INDONESIA_PROVINCES;
}

export function getCitiesByProvince(province: string): string[] {
  return INDONESIA_REGIONS[province] || [];
}

export const DEFAULT_POSTAL_CODES: Record<string, string> = {
  "Jakarta Selatan (Kebayoran, Senopati, SCBD)": "12190",
  "Jakarta Pusat (Menteng, Thamrin, Sudirman)": "10310",
  "Jakarta Barat (Puri Indah, Kebon Jeruk, Tomang)": "11610",
  "Jakarta Utara (PIK, Kelapa Gading, Pluit)": "14470",
  "Jakarta Timur (Rawamangun, Duren Sawit, Cakung)": "13220",
  "Kota Bandung (Dago, Ciumbuleuit, Buahbatu)": "40132",
  "Kota Surabaya (Gubeng, Wonokromo, Pakuwon)": "60281",
  "Kota Malang (Klojen, Lowokwaru, Blimbing)": "65111",
  "Kota Denpasar (Renon, Sanur)": "80234",
  "Kab. Badung (Kuta, Seminyak, Canggu, Nusa Dua)": "80361",
  "Kota Medan": "20111",
  "Kota Semarang (Simpang Lima, Candisari)": "50241",
  "Kota Yogyakarta (Malioboro, Kotagede)": "55122",
  "Kota Makassar": "90111",
  "Kota Balikpapan": "76111",
  "Kota Palembang": "30111",
  "Kota Tangerang Selatan (BSD City, Bintaro, Alam Sutera)": "15310",
};

export function getEstimatedPostalCode(city: string): string {
  if (DEFAULT_POSTAL_CODES[city]) {
    return DEFAULT_POSTAL_CODES[city];
  }
  return "10110";
}
