import { supabase } from "./supabase-db";

export interface CatalogProduct {
  id: string;
  name: string;
  price: number;
  stock: number;
  experienceLevel: "BEGINNER" | "INTERMEDIATE" | "ENTHUSIAST" | "FLAGSHIP";
  soundSignature: "NEUTRAL" | "WARM" | "V_SHAPE" | "BRIGHT" | "BASSHEAD";
  category: string;
  brand: string;
  storeName: string;
  storeCity: string;
  description: string;
  images: string[];
  image: string;
  rating: number;
  reviews: number;
  badge?: string;
  inStock: boolean;
  preOrder: boolean;
}

export const FALLBACK_CATALOG: CatalogProduct[] = [
  {
    id: "prod-ier-z1r",
    name: "Sony IER-Z1R Flagship In-Ear Monitor",
    price: 1699,
    stock: 8,
    experienceLevel: "FLAGSHIP",
    soundSignature: "WARM",
    category: "IN-EAR MONITORS",
    brand: "SONY",
    storeName: "Sony Official Store",
    storeCity: "Jakarta Selatan",
    description: "Flagship HD Hybrid driver system engineered with magnesium alloy and zirconium housing for unmatched soundstage depth and bass authority.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
    rating: 4.9,
    reviews: 64,
    badge: "Flagship",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-ier-m9",
    name: "Sony IER-M9 Audiophile Stage Monitor",
    price: 999,
    stock: 12,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "NEUTRAL",
    category: "IN-EAR MONITORS",
    brand: "SONY",
    storeName: "Sony Official Store",
    storeCity: "Jakarta Selatan",
    description: "5x Balanced Armature stage monitor with magnesium inner housing and integrated audio grade film capacitors.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
    rating: 4.8,
    reviews: 52,
    badge: "Best Seller",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-monarch-mk3",
    name: "Thieaudio Monarch MKIII Tribrid Flagship",
    price: 999,
    stock: 15,
    experienceLevel: "FLAGSHIP",
    soundSignature: "NEUTRAL",
    category: "IN-EAR MONITORS",
    brand: "THIEAUDIO",
    storeName: "Thieaudio Official Store",
    storeCity: "Jakarta Pusat",
    description: "2DD + 6BA + 2EST tribrid system with IMPACT2 isobaric subwoofer for reference analytical monitoring.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    rating: 4.9,
    reviews: 78,
    badge: "Top Rated",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-nanna-2",
    name: "Kinera Imperial Nanna 2.0 PRO",
    price: 949,
    stock: 6,
    experienceLevel: "FLAGSHIP",
    soundSignature: "WARM",
    category: "IN-EAR MONITORS",
    brand: "KINERA",
    storeName: "Kinera Audio Official",
    storeCity: "Surabaya",
    description: "Electrostatic hybrid flagship IEM featuring Sonion EST drivers and custom hand-painted resin shells.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
    rating: 5.0,
    reviews: 45,
    badge: "Artisan Grade",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-ie600",
    name: "Sennheiser IE 600 Audiophile In-Ear",
    price: 699,
    stock: 10,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "V_SHAPE",
    category: "IN-EAR MONITORS",
    brand: "SENNHEISER",
    storeName: "Sennheiser Official Store",
    storeCity: "Jakarta Selatan",
    description: "3D-printed AMLOY-ZR01 amorphous zirconium housing with 7mm TrueResponse transducer.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
    rating: 4.7,
    reviews: 94,
    badge: "Best Seller",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-variations",
    name: "Moondrop Variations Tribrid IEM",
    price: 520,
    stock: 14,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "NEUTRAL",
    category: "IN-EAR MONITORS",
    brand: "MOONDROP",
    storeName: "Moondrop Official Store",
    storeCity: "Bandung",
    description: "1DD + 2BA + 2EST electrostatic hybrid acoustic system tuned precisely to the VDSF target curve.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    rating: 4.8,
    reviews: 112,
    badge: "Community Favorite",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-u12t",
    name: "64 Audio U12t 12-Driver Reference Flagship",
    price: 1999,
    stock: 5,
    experienceLevel: "FLAGSHIP",
    soundSignature: "NEUTRAL",
    category: "IN-EAR MONITORS",
    brand: "64 AUDIO",
    storeName: "Headphone Zone ID",
    storeCity: "Jakarta Barat",
    description: "12 Balanced Armature drivers featuring tia tubeless technology and apex pressure-relieving modules.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
    rating: 5.0,
    reviews: 82,
    badge: "Endgame Tier",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-ie900",
    name: "Sennheiser IE 900 Flagship Beryllium Dynamic",
    price: 1299,
    stock: 7,
    experienceLevel: "FLAGSHIP",
    soundSignature: "V_SHAPE",
    category: "IN-EAR MONITORS",
    brand: "SENNHEISER",
    storeName: "Bass Audio Official",
    storeCity: "Jakarta Selatan",
    description: "Precision-milled aluminum chassis with X3R triple-resonator chamber and 7mm TrueResponse driver.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
    rating: 4.9,
    reviews: 128,
    badge: "Flagship",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-blessing3",
    name: "Moondrop Blessing 3 Hybrid 2DD+4BA",
    price: 319,
    stock: 20,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "NEUTRAL",
    category: "IN-EAR MONITORS",
    brand: "MOONDROP",
    storeName: "Headphone Zone ID",
    storeCity: "Jakarta Barat",
    description: "Horizontally opposed 2DD module (H.O.D.D.D.U.S) with 4 custom balanced armatures for clinical vocal reproduction.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    rating: 4.8,
    reviews: 145,
    badge: "Best Seller",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-ares-s",
    name: "Effect Audio Ares S 4.4mm Balanced Cable",
    price: 179,
    stock: 25,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "WARM",
    category: "ACCESSORIES",
    brand: "EFFECT AUDIO",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "Premium UP-OCC Pure Copper Litz wire with ConX interchangeable connector system.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
    rating: 4.7,
    reviews: 67,
    badge: "Premium Cable",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-mojo2",
    name: "Chord Mojo 2 Portable DAC / Headphone Amp",
    price: 775,
    stock: 9,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "NEUTRAL",
    category: "DAC/AMP",
    brand: "CHORD AUDIO",
    storeName: "Bass Audio Official",
    storeCity: "Jakarta Selatan",
    description: "Custom FPGA-based DAC with lossless Ultra-HD DSP and dual 3.5mm headphone outputs.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
    rating: 4.9,
    reviews: 89,
    badge: "Editor Choice",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-solaris",
    name: "Campfire Audio Solaris Stellar Horizon",
    price: 2670,
    stock: 4,
    experienceLevel: "FLAGSHIP",
    soundSignature: "V_SHAPE",
    category: "IN-EAR MONITORS",
    brand: "CAMPFIRE AUDIO",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "Precision-machined stainless steel housing with brass accents and 3 custom dual-diaphragm balanced armatures.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    rating: 4.8,
    reviews: 31,
    badge: "Collector Edition",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-diva",
    name: "Elysian Acoustic Labs Diva 6BA Masterpiece",
    price: 1599,
    stock: 6,
    experienceLevel: "FLAGSHIP",
    soundSignature: "WARM",
    category: "IN-EAR MONITORS",
    brand: "ELYSIAN",
    storeName: "Headphone Zone ID",
    storeCity: "Jakarta Barat",
    description: "6 Balanced Armature drivers with 3-way rotary bass switch and custom acoustic chamber.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
    rating: 5.0,
    reviews: 42,
    badge: "Vocal Master",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-maestro-mini",
    name: "FatFreq Maestro Mini Sub-bass Cannon",
    price: 429,
    stock: 11,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "BASSHEAD",
    category: "IN-EAR MONITORS",
    brand: "FATFREQ",
    storeName: "Bass Audio Official",
    storeCity: "Jakarta Selatan",
    description: "Patented Bass Cannon technology providing +20dB sub-bass shelf below 200Hz without muddying mid frequencies.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
    rating: 4.9,
    reviews: 73,
    badge: "Bass Monster",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-quintet",
    name: "Kiwi Ears Quintet Quadbrid In-Ear Monitor",
    price: 219,
    stock: 18,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "BRIGHT",
    category: "IN-EAR MONITORS",
    brand: "KIWI EARS",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "Quadbrid design with 1 DLC Dynamic Driver, 2 Balanced Armatures, 1 Planar Magnetic Driver, and 1 PZT conductor.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    rating: 4.7,
    reviews: 65,
    badge: "High Value",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-ea1000",
    name: "Simgot EA1000 Fermat Dynamic In-Ear",
    price: 219,
    stock: 16,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "BRIGHT",
    category: "IN-EAR MONITORS",
    brand: "SIMGOT",
    storeName: "Headphone Zone ID",
    storeCity: "Jakarta Barat",
    description: "Dual-magnetic dual-cavity dynamic driver with 1PR passive radiator for acoustic resonance optimization.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
    rating: 4.8,
    reviews: 84,
    badge: "New Arrival",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-s12pro",
    name: "Letshuoer S12 Pro Planar Magnetic IEM",
    price: 135,
    stock: 22,
    experienceLevel: "BEGINNER",
    soundSignature: "V_SHAPE",
    category: "IN-EAR MONITORS",
    brand: "LETSHUOER",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "14.8mm custom planar magnetic driver with modular cable system (2.5mm / 3.5mm / 4.4mm).",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
    rating: 4.8,
    reviews: 138,
    badge: "Planar King",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-waner",
    name: "Tangzu Wan'er S.G Studio Edition",
    price: 22,
    stock: 40,
    experienceLevel: "BEGINNER",
    soundSignature: "WARM",
    category: "IN-EAR MONITORS",
    brand: "TANGZU",
    storeName: "TANGZU Audio Official Store",
    storeCity: "Jakarta Selatan",
    description: "10mm PET diaphragm dynamic driver tuned for pleasant vocal intimacy and effortless everyday listening.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    rating: 4.7,
    reviews: 310,
    badge: "Budget King",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-nezha",
    name: "Tangzu Nezha Flagship Tribrid 1DD+6BA+1PZT",
    price: 399,
    stock: 12,
    experienceLevel: "FLAGSHIP",
    soundSignature: "NEUTRAL",
    category: "IN-EAR MONITORS",
    brand: "TANGZU",
    storeName: "TANGZU Audio Official Store",
    storeCity: "Jakarta Selatan",
    description: "Tribrid architecture with electro-piezoelectric supertweeter and layered resin acoustic chamber.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
    rating: 4.9,
    reviews: 58,
    badge: "Flagship Tribrid",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-zetian-wu",
    name: "Tangzu x HBB Zetian Wu Heyday Edition Planar",
    price: 199,
    stock: 18,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "WARM",
    category: "IN-EAR MONITORS",
    brand: "TANGZU",
    storeName: "TANGZU Audio Official Store",
    storeCity: "Jakarta Selatan",
    description: "14.5mm planar magnetic transducer in full CNC aluminum housing, tuned in collaboration with HBB.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
    rating: 4.8,
    reviews: 142,
    badge: "Planar Master",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-shimin-li",
    name: "Tangzu Shimin Li Gold Edition Single Dynamic",
    price: 35,
    stock: 25,
    experienceLevel: "BEGINNER",
    soundSignature: "V_SHAPE",
    category: "IN-EAR MONITORS",
    brand: "TANGZU",
    storeName: "TANGZU Audio Official Store",
    storeCity: "Jakarta Selatan",
    description: "10mm N52 dynamic driver with dual cavity acoustic tuning and aviation-grade zinc alloy faceplates.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    rating: 4.6,
    reviews: 89,
    badge: "Entry Grade",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-arya",
    name: "HiFiMAN Arya Stealth Magnet Planar Headphone",
    price: 999,
    stock: 8,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "NEUTRAL",
    category: "HEADPHONE",
    brand: "HIFIMAN",
    storeName: "ShenzhenAudio Official",
    storeCity: "Jakarta Pusat",
    description: "Acoustically invisible stealth magnets with nanometer thickness diaphragm for holographic soundstage.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
    rating: 4.9,
    reviews: 86,
    badge: "Open-Back Reference",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-hd800s",
    name: "Sennheiser HD 800 S Reference Headphone",
    price: 1799,
    stock: 5,
    experienceLevel: "FLAGSHIP",
    soundSignature: "NEUTRAL",
    category: "HEADPHONE",
    brand: "SENNHEISER",
    storeName: "Sennheiser Official Store",
    storeCity: "Jakarta Selatan",
    description: "56mm Ring Radiator transducer with patented absorber technology for uncompressed acoustic staging.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
    rating: 5.0,
    reviews: 79,
    badge: "Audiophile Legend",
    inStock: true,
    preOrder: false,
  },
  // --- NEW 20 DIVERSE & TWS PRODUCTS ---
  {
    id: "prod-wf1000xm5",
    name: "Sony WF-1000XM5 True Wireless Flagship ANC",
    price: 299,
    stock: 25,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "WARM",
    category: "TWS / WIRELESS",
    brand: "SONY",
    storeName: "Sony Official Store",
    storeCity: "Jakarta Selatan",
    description: "Equipped with Dynamic Driver X, dual proprietary processors V2/QN2e, LDAC Hi-Res Audio Wireless, and class-leading noise cancellation.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 180,
    badge: "Flagship TWS",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-momentum-tw4",
    name: "Sennheiser Momentum True Wireless 4",
    price: 299,
    stock: 18,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "NEUTRAL",
    category: "TWS / WIRELESS",
    brand: "SENNHEISER",
    storeName: "Sennheiser Official Store",
    storeCity: "Jakarta Selatan",
    description: "7mm TrueResponse transducer system with Qualcomm S5 Sound Platform, aptX Lossless support, Auracast, and adaptive acoustic tuning.",
    images: ["https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 95,
    badge: "Lossless Audio",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-space-travel",
    name: "Moondrop Space Travel True Wireless ANC",
    price: 25,
    stock: 45,
    experienceLevel: "BEGINNER",
    soundSignature: "NEUTRAL",
    category: "TWS / WIRELESS",
    brand: "MOONDROP",
    storeName: "Moondrop Official Store",
    storeCity: "Bandung",
    description: "13mm Titanium dome dynamic driver with VDSF Target curve calibration, transparent mechanical case design, and 55ms low latency mode.",
    images: ["https://images.unsplash.com/photo-1629367494173-c78a56567877?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1629367494173-c78a56567877?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 320,
    badge: "Best Value TWS",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-qc-ultra-buds",
    name: "Bose QuietComfort Ultra Earbuds",
    price: 299,
    stock: 15,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "WARM",
    category: "TWS / WIRELESS",
    brand: "BOSE",
    storeName: "Headphone Zone ID",
    storeCity: "Jakarta Barat",
    description: "Breakthrough spatialized audio with Bose Immersive Audio and CustomTune technology that tailors sound cancellation to your unique ear shape.",
    images: ["https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 110,
    badge: "King of ANC",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-fokus-prestige",
    name: "Noble Audio FoKus Prestige Audiophile TWS",
    price: 599,
    stock: 8,
    experienceLevel: "FLAGSHIP",
    soundSignature: "V_SHAPE",
    category: "TWS / WIRELESS",
    brand: "NOBLE AUDIO",
    storeName: "Bass Audio Official",
    storeCity: "Jakarta Selatan",
    description: "Hybrid 1DD + 2BA acoustic architecture encapsulated in bespoke handcrafted solid wood shells with Qualcomm TrueWireless Mirroring.",
    images: ["https://images.unsplash.com/photo-1598331668826-20cecc596b86?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1598331668826-20cecc596b86?auto=format&fit=crop&w=800&q=80",
    rating: 5.0,
    reviews: 38,
    badge: "Artisan TWS",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-ze8000-mk2",
    name: "Final Audio ZE8000 MK2 8K Sound TWS",
    price: 399,
    stock: 10,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "NEUTRAL",
    category: "TWS / WIRELESS",
    brand: "FINAL AUDIO",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "Ultra-low distortion f-Core driver paired with dedicated Class-AB amplification and digital FIR filters for extreme clarity and micro-detail resolution.",
    images: ["https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 54,
    badge: "8K Sound",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-airpods-pro2",
    name: "Apple AirPods Pro 2nd Gen (USB-C)",
    price: 249,
    stock: 30,
    experienceLevel: "BEGINNER",
    soundSignature: "NEUTRAL",
    category: "TWS / WIRELESS",
    brand: "APPLE",
    storeName: "Tonal Zone Authorized",
    storeCity: "Jakarta Pusat",
    description: "Powered by Apple H2 headphone processor with 2x Active Noise Cancellation, Adaptive Transparency, and personalized Spatial Audio.",
    images: ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 420,
    badge: "Popular Everyday",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-eah-az80",
    name: "Technics EAH-AZ80 Hi-Fi True Wireless",
    price: 299,
    stock: 14,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "WARM",
    category: "TWS / WIRELESS",
    brand: "TECHNICS",
    storeName: "Bass Audio Official",
    storeCity: "Jakarta Selatan",
    description: "10mm free-edge aluminum diaphragm with acoustic control chamber, industry-first 3-device multipoint pairing, and LDAC wireless audio.",
    images: ["https://images.unsplash.com/photo-1590658002970-d603a11dfb25?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1590658002970-d603a11dfb25?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 86,
    badge: "Hi-Fi Wireless",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-wh1000xm5",
    name: "Sony WH-1000XM5 Wireless Noise Canceling",
    price: 399,
    stock: 20,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "WARM",
    category: "HEADPHONE",
    brand: "SONY",
    storeName: "Sony Official Store",
    storeCity: "Jakarta Selatan",
    description: "Integrated Processor V1 and HD Noise Canceling Processor QN1 controlling 8 microphones with carbon fiber 30mm precision drivers.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 240,
    badge: "Best Travel ANC",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-focal-bathys",
    name: "Focal Bathys Hi-Fi Bluetooth ANC Headphone",
    price: 699,
    stock: 7,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "NEUTRAL",
    category: "HEADPHONE",
    brand: "FOCAL",
    storeName: "Headphone Zone ID",
    storeCity: "Jakarta Barat",
    description: "Made in France Aluminum/Magnesium M-dome speaker drivers with integrated USB-DAC mode supporting native 24-bit/192kHz high-resolution audio.",
    images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 62,
    badge: "Audiophile Wireless",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-m50x-bt2",
    name: "Audio-Technica ATH-M50xBT2 Wireless Studio",
    price: 199,
    stock: 22,
    experienceLevel: "BEGINNER",
    soundSignature: "V_SHAPE",
    category: "HEADPHONE",
    brand: "AUDIO-TECHNICA",
    storeName: "Tonal Zone Authorized",
    storeCity: "Jakarta Pusat",
    description: "Legendary M50x sonic signature with 45mm large-aperture drivers, dedicated AK4331 audio DAC, low latency mode, and 50-hour battery life.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 175,
    badge: "Studio Classic",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-meze-109pro",
    name: "Meze Audio 109 PRO Dynamic Open-Back",
    price: 799,
    stock: 6,
    experienceLevel: "ENTHUSIAST",
    soundSignature: "WARM",
    category: "HEADPHONE",
    brand: "MEZE AUDIO",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "50mm dynamic driver with Beryllium-coated polymer dome and carbon fiber cellulose composite, housed in sustainably harvested Black Walnut earcups.",
    images: ["https://images.unsplash.com/photo-1577174881658-0f30ed549adc?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1577174881658-0f30ed549adc?auto=format&fit=crop&w=800&q=80",
    rating: 5.0,
    reviews: 58,
    badge: "Acoustic Art",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-fiio-btr7",
    name: "FiiO BTR7 Portable Bluetooth DAC & Amp",
    price: 199,
    stock: 20,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "NEUTRAL",
    category: "DAC/AMP",
    brand: "FIIO",
    storeName: "Bass Audio Official",
    storeCity: "Jakarta Selatan",
    description: "Dual ES9219C DACs with THX AAA-28 amplifier architecture, 3.5mm SE + 4.4mm balanced output, color IPS display, and Qi wireless charging.",
    images: ["https://images.unsplash.com/photo-1558089687-f282ffcbc126?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1558089687-f282ffcbc126?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 140,
    badge: "THX Certified",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-ifi-goblu",
    name: "iFi Audio GO blu Ultra-Portable Bluetooth DAC",
    price: 199,
    stock: 16,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "WARM",
    category: "DAC/AMP",
    brand: "IFI AUDIO",
    storeName: "Headphone Zone ID",
    storeCity: "Jakarta Barat",
    description: "Cirrus Logic 32-bit DAC with DirectDrive analog circuitry, XBass and XSpace analog sound enhancement, and 4.4mm balanced output in a matchbox size.",
    images: ["https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 92,
    badge: "Pocket Powerhouse",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-qudelix-5k",
    name: "Qudelix-5K Bluetooth USB DAC / Parametric EQ",
    price: 109,
    stock: 25,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "NEUTRAL",
    category: "DAC/AMP",
    brand: "QUDELIX",
    storeName: "Tonal Zone Authorized",
    storeCity: "Jakarta Pusat",
    description: "Dual ES9218p Sabre DACs with full 20-band hardware Parametric EQ app integration, LDAC/aptX Adaptive, and 2.5mm balanced output.",
    images: ["https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 215,
    badge: "DSP Master",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-dawn-pro",
    name: "Moondrop Dawn Pro Dual CS43131 Type-C Dongle",
    price: 49,
    stock: 35,
    experienceLevel: "BEGINNER",
    soundSignature: "NEUTRAL",
    category: "DAC/AMP",
    brand: "MOONDROP",
    storeName: "Moondrop Official Store",
    storeCity: "Bandung",
    description: "Dual Cirrus Logic CS43131 decoding chips in full CNC aluminum housing with 100-step hardware volume control and dual 3.5mm/4.4mm ports.",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 190,
    badge: "Budget Dongle King",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-dx3-pro-plus",
    name: "Topping DX3 Pro+ Desktop DAC & Headphone Amp",
    price: 199,
    stock: 12,
    experienceLevel: "INTERMEDIATE",
    soundSignature: "NEUTRAL",
    category: "DAC/AMP",
    brand: "TOPPING",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "ESS ES9038Q2M DAC chip with NFCA headphone amplification, Bluetooth 5.0 LDAC receiver, USB/Optical/Coaxial inputs, and remote control.",
    images: ["https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 130,
    badge: "Desktop Value",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-zero-red",
    name: "Truthear x Crinacle ZERO:RED Dual Dynamic",
    price: 55,
    stock: 30,
    experienceLevel: "BEGINNER",
    soundSignature: "NEUTRAL",
    category: "IN-EAR MONITORS",
    brand: "TRUTHEAR",
    storeName: "ShenzhenAudio Official",
    storeCity: "Jakarta Pusat",
    description: "Dual dynamic driver (10mm + 7.8mm) with polyurethane suspension composite liquid crystal dome, tuned to the Crinacle Target with optional 10Ω bass adapter.",
    images: ["https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 350,
    badge: "Community Benchmark",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-7hz-zero",
    name: "7Hz Salnotes Zero High-Performance IEM",
    price: 20,
    stock: 50,
    experienceLevel: "BEGINNER",
    soundSignature: "NEUTRAL",
    category: "IN-EAR MONITORS",
    brand: "7HZ",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "10mm dynamic driver with metal composite diaphragm, precision acoustic cavity, and detachable 0.78mm 2-pin silver-plated OFC cable.",
    images: ["https://images.unsplash.com/photo-1598331668826-20cecc596b86?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1598331668826-20cecc596b86?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 410,
    badge: "Entry Benchmark",
    inStock: true,
    preOrder: false,
  },
  {
    id: "prod-kiwi-cadenza",
    name: "Kiwi Ears Cadenza 10mm Beryllium Dynamic",
    price: 35,
    stock: 28,
    experienceLevel: "BEGINNER",
    soundSignature: "WARM",
    category: "IN-EAR MONITORS",
    brand: "KIWI EARS",
    storeName: "Linsoul Audio",
    storeCity: "Surabaya",
    description: "10mm large Beryllium diaphragm dynamic driver in 3D-printed medical-grade resin shell, tuned for smooth audiophile vocal warmth and engaging bass response.",
    images: ["https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80"],
    image: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 260,
    badge: "Vocal Warmth",
    inStock: true,
    preOrder: false,
  },
];

export async function fetchProductsFromDb(): Promise<CatalogProduct[]> {
  try {
    const { data, error } = await supabase
      .from("Product")
      .select(`
        id,
        name,
        price,
        stock,
        experienceLevel,
        soundSignature,
        images,
        description,
        brand:Brand(name),
        store:Store(storeName, address),
        category:Category(name)
      `)
      .order("price", { ascending: false });

    if (!error && data && data.length > 0) {
      const dbProducts = data.map((item: any, index: number) => {
        const brandName = Array.isArray(item.brand) ? item.brand[0]?.name : item.brand?.name || "Audiophile";
        const storeName = Array.isArray(item.store) ? item.store[0]?.storeName : item.store?.storeName || "TonalZone Partner";
        const storeCity = Array.isArray(item.store) ? item.store[0]?.address : item.store?.address || "Jakarta";
        const catName = Array.isArray(item.category) ? item.category[0]?.name : item.category?.name || "IN-EAR MONITORS";
        const imgList = Array.isArray(item.images) && item.images.length > 0 ? item.images : ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"];

        return {
          id: item.id,
          name: item.name,
          price: Number(item.price) || 99,
          stock: Number(item.stock) || 10,
          experienceLevel: item.experienceLevel || "INTERMEDIATE",
          soundSignature: item.soundSignature || "NEUTRAL",
          category: catName,
          brand: brandName,
          storeName,
          storeCity,
          description: item.description || "Audiophile Reference Gear",
          images: imgList,
          image: imgList[0],
          rating: 4.7 + (index % 4) * 0.1,
          reviews: 24 + (index * 7) % 180,
          badge: index < 6 ? "Best Seller" : index % 5 === 0 ? "New Arrival" : undefined,
          inStock: (Number(item.stock) || 10) > 0,
          preOrder: (Number(item.stock) || 10) <= 2,
        };
      });

      // Merge with fallback products if DB has fewer items to ensure a rich full grid
      if (dbProducts.length < 20) {
        const existingNames = new Set(dbProducts.map((p) => p.name.toLowerCase()));
        const additional = FALLBACK_CATALOG.filter((p) => !existingNames.has(p.name.toLowerCase()));
        return [...dbProducts, ...additional];
      }

      return dbProducts;
    }

    return FALLBACK_CATALOG;
  } catch (err) {
    console.error("[Products DB] Exception while fetching:", err);
    return FALLBACK_CATALOG;
  }
}

export async function fetchProductByIdFromDb(id: string): Promise<CatalogProduct | null> {
  try {
    const { data, error } = await supabase
      .from("Product")
      .select(`
        id,
        name,
        price,
        stock,
        experienceLevel,
        soundSignature,
        images,
        description,
        brand:Brand(name),
        store:Store(storeName, address),
        category:Category(name)
      `)
      .eq("id", id)
      .single();

    if (!error && data) {
      const item: any = data;
      const brandName = Array.isArray(item.brand) ? item.brand[0]?.name : item.brand?.name || "Audiophile";
      const storeName = Array.isArray(item.store) ? item.store[0]?.storeName : item.store?.storeName || "TonalZone Partner";
      const storeCity = Array.isArray(item.store) ? item.store[0]?.address : item.store?.address || "Jakarta";
      const catName = Array.isArray(item.category) ? item.category[0]?.name : item.category?.name || "IN-EAR MONITORS";
      const imgList = Array.isArray(item.images) && item.images.length > 0 ? item.images : ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800"];

      return {
        id: data.id,
        name: data.name,
        price: Number(data.price) || 99,
        stock: Number(data.stock) || 10,
        experienceLevel: data.experienceLevel || "INTERMEDIATE",
        soundSignature: data.soundSignature || "NEUTRAL",
        category: catName,
        brand: brandName,
        storeName,
        storeCity,
        description: data.description || "Audiophile Reference Gear",
        images: imgList,
        image: imgList[0],
        rating: 4.9,
        reviews: 48,
        inStock: (Number(data.stock) || 10) > 0,
        preOrder: false,
      };
    }

    const fallback = FALLBACK_CATALOG.find((p) => p.id === id || p.id.includes(id));
    return fallback || FALLBACK_CATALOG[0];
  } catch (err) {
    console.error("[Products DB] Exception while fetching by ID:", err);
    const fallback = FALLBACK_CATALOG.find((p) => p.id === id || p.id.includes(id));
    return fallback || FALLBACK_CATALOG[0];
  }
}
